org: paulocarvalho
app: desafio-bgc
service: desafio-bgc
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  runtime: nodejs18.x

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*  # Voltar aqui para definir somente as ações utilizadas 
          Resource: "arn:aws:dynamodb:us-east-1:922482202435:table/amazon-products"


functions:
  api:
    handler: /src/api/index.handler
    events:
      - httpApi:
          path: /api
          method: get
	
  getSearches:
    handler: /src/getSearches/index.handler
    events:
      - httpApi:
          path: /searches
          method: get
    environment:
      DYNAMODB_TABLE: amazon-products

  #getSearch:
    #handler: /src/getSearch/index.handler
    #events:
      #- httpApi:
          #path: /search
          #method: get

  scraper:
    handler: /src/scraper/index.handler
    

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: amazon-products
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5	
          WriteCapacityUnits: 5
